version: '2'
services:
    pruebamavha-app:
        image: pruebamavha
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://pruebamavha-mariadb:3306/pruebamavha
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    pruebamavha-mariadb:
        extends:
            file: mariadb.yml
            service: pruebamavha-mariadb
